# Generated by Django 3.2.4 on 2022-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chatphone_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cp_items_col',
            },
        ),
    ]
