# Generated by Django 3.2.10 on 2022-01-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatphone_items',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
