# Generated by Django 3.1.14 on 2022-01-31 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_teesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mentee_question_col',
            fields=[
                ('mentee_qus_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thesis_plan_Id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('mentee_qus', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='mentor_answer_col',
            fields=[
                ('mentor_ans_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mentor_ans', models.TextField()),
                ('mentee_question_Id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('user_Id', models.IntegerField()),
            ],
        ),
    ]
