# Generated by Django 3.1.14 on 2022-02-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_teesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_col',
            fields=[
                ('search_Id', models.AutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(blank=True, max_length=128)),
                ('career', models.TextField(blank=True)),
            ],
        ),
    ]
