# Generated by Django 3.1.14 on 2022-02-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_teesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_answer_col',
            fields=[
                ('c_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_ans', models.TextField()),
                ('c_question_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='c_question_col',
            fields=[
                ('c_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_que', models.TextField()),
                ('que_classification_id', models.IntegerField()),
            ],
        ),
    ]
