# Generated by Django 3.1.14 on 2022-01-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_teesis', '0002_mentee_question_col_mentor_answer_col'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentee_question_col',
            old_name='mentee_qus',
            new_name='mentee_question',
        ),
        migrations.RenameField(
            model_name='mentee_question_col',
            old_name='mentee_qus_Id',
            new_name='mentee_question_Id',
        ),
        migrations.RenameField(
            model_name='mentor_answer_col',
            old_name='mentor_ans',
            new_name='mentor_answer',
        ),
        migrations.RenameField(
            model_name='mentor_answer_col',
            old_name='mentor_ans_Id',
            new_name='mentor_answer_Id',
        ),
    ]
