# Generated by Django 3.1.14 on 2022-02-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_teesis', '0002_c_answer_col_c_question_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_info_col',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Id', models.IntegerField()),
                ('major', models.CharField(blank=True, max_length=128)),
                ('subject', models.CharField(blank=True, max_length=128)),
                ('tag', models.CharField(blank=True, max_length=128)),
            ],
        ),
    ]
